'use client';

import { useState, useCallback } from 'react';
import { parsePhotos, parseExifToolCSV } from '@/lib/exif-parser';
import { buildTimeline } from '@/lib/timeline-engine';
import { saveTimeline, saveImportSession } from '@/lib/storage';
import type { TimelineEntry } from '@/types';

interface FileUploadProps {
  year: number;
  onImportComplete: (entries: TimelineEntry[]) => void;
}

export default function FileUpload({ year, onImportComplete }: FileUploadProps) {
  const [dragOver, setDragOver] = useState(false);
  const [processing, setProcessing] = useState(false);
  const [progress, setProgress] = useState('');
  const [mode, setMode] = useState<'photo' | 'csv'>('photo');

  const handleFiles = useCallback(async (files: File[]) => {
    if (files.length === 0) return;
    setProcessing(true);

    try {
      if (mode === 'csv') {
        setProgress('Parsing CSV...');
        const text = await files[0].text();
        const records = parseExifToolCSV(text);
        setProgress(`Found ${records.length} geotagged records. Building timeline...`);
        const timeline = buildTimeline(records, year);
        await saveTimeline(timeline);
        await saveImportSession({
          id: crypto.randomUUID(),
          timestamp: new Date(),
          source: 'csv-import',
          recordCount: records.length,
        });
        onImportComplete(timeline);
        setProgress(`Imported ${records.length} records.`);
      } else {
        setProgress(`Processing ${files.length} photos...`);
        // Process in batches to avoid memory issues
        const BATCH = 100;
        const allRecords = [];
        for (let i = 0; i < files.length; i += BATCH) {
          const batch = files.slice(i, i + BATCH);
          setProgress(`Processing photos ${i + 1}-${Math.min(i + BATCH, files.length)} of ${files.length}...`);
          const records = await parsePhotos(batch);
          allRecords.push(...records);
        }
        setProgress(`Found ${allRecords.length} geotagged photos. Building timeline...`);
        const timeline = buildTimeline(allRecords, year);
        await saveTimeline(timeline);
        await saveImportSession({
          id: crypto.randomUUID(),
          timestamp: new Date(),
          source: 'photo-upload',
          recordCount: allRecords.length,
        });
        onImportComplete(timeline);
        setProgress(`Imported ${allRecords.length} geotagged photos.`);
      }
    } catch (err) {
      setProgress(`Error: ${err instanceof Error ? err.message : 'Unknown error'}`);
    } finally {
      setProcessing(false);
    }
  }, [mode, year, onImportComplete]);

  const onDrop = useCallback((e: React.DragEvent) => {
    e.preventDefault();
    setDragOver(false);
    const files = Array.from(e.dataTransfer.files);
    handleFiles(files);
  }, [handleFiles]);

  const onFileSelect = useCallback((e: React.ChangeEvent<HTMLInputElement>) => {
    const files = Array.from(e.target.files || []);
    handleFiles(files);
  }, [handleFiles]);

  return (
    <div className="space-y-4">
      <div className="flex gap-2">
        <button
          onClick={() => setMode('photo')}
          className={`px-4 py-2 rounded-lg text-sm font-medium transition-colors ${
            mode === 'photo'
              ? 'bg-blue-600 text-white'
              : 'bg-gray-700 text-gray-300 hover:bg-gray-600'
          }`}
        >
          Upload Photos
        </button>
        <button
          onClick={() => setMode('csv')}
          className={`px-4 py-2 rounded-lg text-sm font-medium transition-colors ${
            mode === 'csv'
              ? 'bg-blue-600 text-white'
              : 'bg-gray-700 text-gray-300 hover:bg-gray-600'
          }`}
        >
          Import ExifTool CSV
        </button>
      </div>

      <div
        onDrop={onDrop}
        onDragOver={(e) => { e.preventDefault(); setDragOver(true); }}
        onDragLeave={() => setDragOver(false)}
        className={`border-2 border-dashed rounded-xl p-8 text-center transition-colors ${
          dragOver
            ? 'border-blue-500 bg-blue-500/10'
            : 'border-gray-600 hover:border-gray-500'
        } ${processing ? 'opacity-50 pointer-events-none' : ''}`}
      >
        <div className="space-y-3">
          <div className="text-4xl">
            {mode === 'photo' ? '📷' : '📄'}
          </div>
          <div>
            <p className="text-gray-200 font-medium">
              {mode === 'photo'
                ? 'Drop photos here or click to browse'
                : 'Drop ExifTool CSV here or click to browse'}
            </p>
            <p className="text-gray-400 text-sm mt-1">
              {mode === 'photo'
                ? 'Only EXIF headers are read — pixel data is never loaded'
                : 'Upload the CSV generated by ExifTool'}
            </p>
          </div>
          <label className="inline-block">
            <span className="px-4 py-2 bg-blue-600 hover:bg-blue-700 text-white rounded-lg cursor-pointer text-sm font-medium transition-colors">
              Choose Files
            </span>
            <input
              type="file"
              className="hidden"
              multiple={mode === 'photo'}
              accept={mode === 'photo' ? 'image/*' : '.csv'}
              onChange={onFileSelect}
              disabled={processing}
            />
          </label>
        </div>
      </div>

      {progress && (
        <div className="flex items-center gap-2 text-sm">
          {processing && (
            <div className="w-4 h-4 border-2 border-blue-500 border-t-transparent rounded-full animate-spin" />
          )}
          <span className={processing ? 'text-blue-400' : 'text-green-400'}>{progress}</span>
        </div>
      )}
    </div>
  );
}
